<?php
$irregularVerbs = [
    ['be',        'was / were','been',      'ser'],
    ['beat',      'beat',      'beaten',    'golpear'],
    ['become',    'became',    'become',    'llegar a ser'],
    ['begin',     'began',     'begun',     'empezar'],
    ['bend',      'bent',      'bent',      'doblar'],
    ['bet',       'bet',       'bet',       'apostar'],
    ['bite',      'bit',       'bitten',    'morder'],
    ['bleed',     'bled',      'bled',      'sangrar'],
    ['blow',      'blew',      'blown',     'soplar'],
    ['break',     'broke',     'broken',    'romper'],
    ['bring',     'brought',   'brought',   'traer'],
    ['build',     'built',     'built',     'construir'],
    ['burn',      'burnt',     'burnt',     'quemar'],
    ['burst',     'burst',     'burst',     'estallar'],
    ['buy',       'bought',    'bought',    'comprar'],
    ['catch',     'caught',    'caught',    'coger'],
    ['choose',    'chose',     'chosen',    'elegir'],
    ['come',      'came',      'come',      'venir'],
    ['cost',      'cost',      'cost',      'costar'],
    ['cut',       'cut',       'cut',       'cortar'],
    ['deal',      'dealt',     'dealt',     'tratar'],
    ['dig',       'dug',       'dug',       'cavar'],
    ['do',        'did',       'done',      'hacer'],
    ['draw',      'drew',      'drawn',     'dibujar'],
    ['dream',     'dreamt',    'dreamt',    'soñar'],
    ['drink',     'drank',     'drunk',     'beber'],
    ['drive',     'drove',     'driven',    'conducir'],
    ['eat',       'ate',       'eaten',     'comer'],
    ['fall',      'fell',      'fallen',    'caer'],
    ['feed',      'fed',       'fed',       'alimentar'],
    ['feel',      'felt',      'felt',      'sentir'],
    ['fight',     'fought',    'fought',    'luchar'],
    ['find',      'found',     'found',     'encontrar'],
    ['fly',       'flew',      'flown',     'volar'],
    ['forget',    'forgot',    'forgotten', 'olvidar'],
    ['forgive',   'forgave',   'forgiven',  'perdonar'],
    ['freeze',    'froze',     'frozen',    'congelar'],
    ['get',       'got',       'got',       'conseguir'],
    ['give',      'gave',      'given',     'dar'],
    ['go',        'went',      'gone',      'ir'],
    ['grow',      'grew',      'grown',     'crecer'],
    ['hang',      'hung',      'hung',      'colgar'],
    ['have',      'had',       'had',       'tener'],
    ['hear',      'heard',     'heard',     'oír'],
    ['hide',      'hid',       'hidden',    'esconder'],
    ['hit',       'hit',       'hit',       'golpear'],
    ['hold',      'held',      'held',      'sujetar'],
    ['hurt',      'hurt',      'hurt',      'herir'],
    ['keep',      'kept',      'kept',      'mantener'],
    ['know',      'knew',      'known',     'saber'],
    ['lay',       'laid',      'laid',      'extender'],
    ['lead',      'led',       'led',       'guiar'],
    ['learn',     'learnt',    'learnt',    'aprender'],
    ['leave',     'left',      'left',      'marcharse'],
    ['lend',      'lent',      'lent',      'prestar'],
    ['let',       'let',       'let',       'permitir'],
    ['lie',       'lay',       'lain',      'tumbarse'],
    ['light',     'lit',       'lit',       'encender'],
    ['lose',      'lost',      'lost',      'perder'],
    ['make',      'made',      'made',      'fabricar'],
    ['mean',      'meant',     'meant',     'significar'],
    ['meet',      'met',       'met',       'conocer a'],
    ['pay',       'paid',      'paid',      'pagar'],
    ['put',       'put',       'put',       'poner'],
    ['read',      'read',      'read',      'leer'],
    ['ride',      'rode',      'ridden',    'montar'],
    ['ring',      'rang',      'rung',      'llamar'],
    ['rise',      'rose',      'risen',     'elevar'],
    ['run',       'ran',       'run',       'correr'],
    ['say',       'said',      'said',      'decir'],
    ['see',       'saw',       'seen',      'ver'],
    ['sell',      'sold',      'sold',      'vender'],
    ['send',      'sent',      'sent',      'enviar'],
    ['set',       'set',       'set',       'colocar'],
    ['sew',       'sewed',     'sewn',      'coser'],
    ['shake',     'shook',     'shaken',    'agitar'],
    ['shine',     'shone',     'shone',     'brillar'],
    ['shoot',     'shot',      'shot',      'disparar'],
    ['show',      'showed',    'shown',     'mostrar'],
    ['shut',      'shut',      'shut',      'cerrar'],
    ['sing',      'sang',      'sung',      'cantar'],
    ['sink',      'sank',      'sunk',      'hundirse'],
    ['sit',       'sat',       'sat',       'sentarse'],
    ['sleep',     'slept',     'slept',     'dormir'],
    ['smell',     'smelt',     'smelt',     'oler'],
    ['speak',     'spoke',     'spoken',    'hablar un idioma'],
    ['spell',     'spelt',     'spelt',     'deletrear'],
    ['spend',     'spent',     'spent',     'gastar'],
    ['spill',     'spilt',     'spilt',     'derramarse'],
    ['spoil',     'spoilt',    'spoilt',    'estropear'],
    ['spread',    'spread',    'spread',    'untar'],
    ['spring',    'sprang',    'sprung',    'saltar'],
    ['stand',     'stood',     'stood',     'estar de pie'],
    ['steal',     'stole',     'stolen',    'robar'],
    ['stick',     'stuck',     'stuck',     'pegar'],
    ['sting',     'stung',     'stung',     'picar'],
    ['swear',     'swore',     'sworn',     'jurar'],
    ['sweep',     'swept',     'swept',     'barrer'],
    ['swim',      'swam',      'swum',      'nadar'],
    ['take',      'took',      'taken',     'tomar'],
    ['teach',     'taught',    'taught',    'enseñar'],
    ['tear',      'tore',      'torn',      'desgarrar'],
    ['tell',      'told',      'told',      'contar'],
    ['think',     'thought',   'thought',   'pensar'],
    ['throw',     'threw',     'thrown',    'tirar'],
    ['understand','understood','understood','comprender'],
    ['wake up',   'woke up',   'woken up',  'despertarse'],
    ['wear',      'wore',      'worn',      'llevar puesto'],
    ['win',       'won',       'won',       'ganar'],
    ['write',     'wrote',     'written',   'escribir']
];
